"""The station image (Raspberry Pi OS Lite) and the checks of the ``image.*`` settings.

The image is the same for every board: rpi-image-gen builds Raspberry Pi OS Lite from the station layers
in ``image/layer`` -- ``otp-rpios-packages`` (the package set of the official release, generated by
``image/rpios_packages.py``), ``otp-rpios-lite`` (the suite: rpi-image-gen's Debian and Raspberry Pi base
plus those packages, with the documentation the official image has) and ``otp-rpios-setup`` (what pi-gen
configures beyond packages: the first user ``pi`` locked without a login shell, SSH off, Wi-Fi off until a
country is set, en_GB / gb / Europe/London, the NoCloud templates in /boot/firmware). The only build
setting is ``image.name``; the provisioning map (``IGconf_image_pmap``, clear or crypt) is an override
per image variant.

Everything else in ``image.*`` -- host name, time zone, account, SSH, Wi-Fi -- is per board: stage 3
writes it to the board's boot partition as cloud-init files (:mod:`otp_server.firstboot`), so saving those
settings rebuilds nothing.

The value checks (``check_*``) are shared with :mod:`otp_server.config`, which validates the settings.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from typing import Any

from . import firstboot, image_choices
from .passhash import is_crypt_hash

CONFIG_NAME = "otp-image.yaml"
#: Partition sizes of the image (rpi-image-gen image-rpios layer).
BOOT_PART_SIZE = "200%"
ROOT_PART_SIZE = "300%"
#: The image as pi-gen leaves it: host name and first user before cloud-init or the wizard set them up.
IMAGE_HOSTNAME = "raspberrypi"
IMAGE_USER = "pi"
#: pi-gen's groups of the first user (rpi-image-gen adds ``sudo`` itself through ``user1sudo``).
IMAGE_USER_GROUPS = "adm,dialout,cdrom,audio,users,video,games,plugdev,input,gpio,spi,i2c,netdev,render"

_IMAGE_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
_HOSTNAME_RE = re.compile(r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$")
_USER_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")
_HEX64_RE = re.compile(r"^[0-9a-fA-F]{64}$")
_KEY_TYPES = ("ssh-ed25519", "ssh-rsa", "ssh-dss", "ecdsa-sha2-nistp256", "ecdsa-sha2-nistp384",
              "ecdsa-sha2-nistp521", "sk-ssh-ed25519@openssh.com", "sk-ecdsa-sha2-nistp256@openssh.com")
_KEY_RE = re.compile(r"(?:^|\s)(?:" + "|".join(re.escape(t) for t in _KEY_TYPES) + r") [A-Za-z0-9+/]{16,}={0,3}(?:\s|$)")
#: System accounts and groups of Raspberry Pi OS Lite: the first user and its group are renamed to the
#: chosen name (userconf), so it must not be one of these.
RESERVED_USERS = frozenset({
    "root", "daemon", "bin", "sys", "sync", "games", "man", "lp", "mail", "news", "uucp", "proxy", "www-data",
    "backup", "list", "irc", "_apt", "nobody", "systemd-network", "dhcpcd", "systemd-timesync", "messagebus",
    "sshd", "dnsmasq", "avahi", "polkitd",
    "adm", "tty", "disk", "kmem", "dialout", "fax", "voice", "cdrom", "floppy", "tape", "sudo", "audio", "dip",
    "operator", "src", "shadow", "utmp", "video", "sasl", "plugdev", "staff", "users", "nogroup",
    "systemd-journal", "crontab", "input", "sgx", "clock", "kvm", "render", "_ssh", "netdev", "bluetooth",
    "spi", "i2c", "gpio"})
#: A serial for checking host name templates.
_SAMPLE_SERIAL = "0123abcd"


# ------------------------------------------------------------------ checks (raise ValueError)
def check_image_name(v: str) -> str:
    if not _IMAGE_NAME_RE.fullmatch(v):
        raise ValueError(f"image name {v!r}: letters, digits, '.', '_' and '-' only (up to 64)")
    return v


def check_hostname(v: str) -> str:
    """A host name, or a template with ``{serial}`` (the 8-hex board serial) in it."""
    v = v.strip().lower()
    rest = v.replace(firstboot.SERIAL_PLACEHOLDER, "")
    if "{" in rest or "}" in rest:
        raise ValueError(f"hostname {v!r}: the only placeholder is {firstboot.SERIAL_PLACEHOLDER}")
    if not _HOSTNAME_RE.fullmatch(firstboot.hostname_for(v, _SAMPLE_SERIAL)):
        raise ValueError(f"hostname {v!r}: lower-case letters, digits and '-' (not at either end), up to 63 "
                         f"with {firstboot.SERIAL_PLACEHOLDER} counted as 8 characters")
    return v


def check_user(v: str) -> str:
    v = v.strip()
    if not _USER_RE.fullmatch(v):
        raise ValueError(f"user name {v!r}: starts with a lower-case letter or '_', then lower-case letters, "
                         "digits, '_' or '-' (up to 32)")
    if v in RESERVED_USERS:
        raise ValueError(f"user name {v!r} is a system account; pick another")
    return v


def check_timezone(v: str) -> str:
    v = v.strip()
    if not image_choices.is_timezone(v):
        raise ValueError(f"time zone {v!r} is not in the image's tzdata: pick one from the list (Europe/Kyiv, UTC, ...)")
    return v


def check_keyboard(v: str) -> str:
    v = v.strip()
    if not image_choices.is_keyboard(v):
        raise ValueError(f"keyboard layout {v!r} is not in the image's xkb-data: pick one from the list (us, gb, ua, ...)")
    return v


def check_password_hash(v: str) -> str:
    v = v.strip()
    if v and not is_crypt_hash(v):
        raise ValueError("the password hash must be a crypt(3) hash such as $6$... (set the password on the page, "
                         "or paste the output of: openssl passwd -6)")
    return v


def check_ssid(v: str) -> str:
    if v != v.strip():
        raise ValueError("Wi-Fi network name: no spaces at either end")
    if len(v.encode("utf-8")) > 32:
        raise ValueError(f"Wi-Fi network name {v!r} is longer than 32 bytes")
    if any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in v):
        raise ValueError("Wi-Fi network name: control characters are not allowed")
    return v


def check_wifi_password(v: str) -> str:
    """Empty (open network), an 8..63 character passphrase (printable ASCII) or a 64-digit hex PSK."""
    if not v:
        return v
    if _HEX64_RE.fullmatch(v):
        return v.lower()
    if not 8 <= len(v) <= 63:
        raise ValueError("Wi-Fi password: 8 to 63 characters (or a 64-digit hex key; empty = open network)")
    if any(not 0x20 <= ord(ch) <= 0x7E for ch in v):
        raise ValueError("Wi-Fi password: printable ASCII characters only (WPA passphrase)")
    return v


def check_country(v: str) -> str:
    v = v.strip().upper()
    if not image_choices.is_country(v):
        raise ValueError(f"Wi-Fi country {v!r} is not in wireless-regdb: pick one from the list (UA, PL, ...; 00 = world)")
    return v


def check_authorized_key(line: str) -> str:
    line = line.strip()
    if not _KEY_RE.search(line):
        raise ValueError(f"not an OpenSSH public key line: {line[:40]!r}... (expected 'ssh-ed25519 AAAA... comment')")
    return line


# ------------------------------------------------------------------ the page / status view
def public_view(img: Any) -> dict:
    """The settings without secrets (status, manifests, logs)."""
    return {
        "name": img.name,
        "hostname": img.hostname,
        "timezone": img.timezone,
        "keyboard": img.keyboard,
        "user": img.user,
        "password_set": bool(img.password_hash),
        "sudo": firstboot.sudo_mode(img),
        "ssh": bool(img.ssh),
        "ssh_password_login": bool(img.ssh_password_login),
        "ssh_authorized_keys": len(img.ssh_authorized_keys),
        "wifi_ssid": img.wifi_ssid,
        "wifi_password_set": bool(img.wifi_password),
        "wifi_country": img.wifi_country,
        "wifi_hidden": bool(img.wifi_hidden),
    }


def warnings(img: Any) -> list[str]:
    """What the operator should know about these settings (nothing here stops provisioning)."""
    out: list[str] = []
    if not firstboot.has_account(img):
        out.append("no password and no SSH key: the board's first boot stops at the Raspberry Pi OS wizard on "
                   "its console (screen and keyboard), which asks for a user name and password")
    if img.ssh and not img.ssh_password_login and not img.ssh_authorized_keys:
        out.append("SSH is on but password login is off and there is no key: SSH lets nobody in")
    if img.ssh and img.ssh_password_login and not img.password_hash and img.ssh_authorized_keys:
        out.append("SSH password login is on but no password is set: only the keys work")
    if img.wifi_ssid and not img.wifi_password:
        out.append(f"Wi-Fi {img.wifi_ssid!r} has no password: the board joins it as an open network")
    if img.wifi_country == "00":
        out.append("Wi-Fi country 00 (world) limits channels and power; set the country the boards fly in")
    if firstboot.SERIAL_PLACEHOLDER not in img.hostname:
        out.append(f"every board gets the host name {img.hostname!r}; put {firstboot.SERIAL_PLACEHOLDER} in it "
                   "(e.g. pi5-{serial}) to tell them apart on the network")
    return out


# ------------------------------------------------------------------ rendering
@dataclass
class RenderedConfig:
    """The config text, the files it needs next to it (path relative to the config dir -> bytes; none at
    the moment) and a public summary."""

    text: str
    files: dict[str, bytes] = field(default_factory=dict)
    summary: dict = field(default_factory=dict)

    def digest(self) -> str:
        """sha256 over the config and every file (names and contents): changes whenever the image would."""
        h = hashlib.sha256(self.text.encode("utf-8"))
        for name in sorted(self.files):
            h.update(b"\0" + name.encode("utf-8") + b"\0" + self.files[name])
        return h.hexdigest()


def _q(value: str) -> str:
    """A YAML double-quoted scalar of an already validated plain value (no quotes, backslashes, controls)."""
    if any(ch in value for ch in '"\\') or any(ord(ch) < 0x20 for ch in value):
        raise ValueError(f"unexpected character in config value {value!r}")
    return f'"{value}"'


def render(img: Any, *, mount: str = "/cfg") -> RenderedConfig:
    """The rpi-image-gen config of the station image named ``img.name``. ``mount`` (where the build
    container sees the config dir) is unused while the config needs no files next to it."""
    del mount
    lines = [
        "# rpi-image-gen config written by OTP_Provisioner: Raspberry Pi OS Lite for the Raspberry Pi 5.",
        "# The same image for every board; stage 3 writes each board's account, SSH, Wi-Fi, host name and",
        "# time zone to its boot partition as cloud-init files (image.* settings).",
        "device:",
        "  layer: rpi5",
        f"  hostname: {_q(IMAGE_HOSTNAME)}",
        f"  user1: {_q(IMAGE_USER)}",
        '  user1sudo: "passwd"',
        f"  user1groups: {_q(IMAGE_USER_GROUPS)}",
        "",
        "image:",
        "  layer: image-rpios",
        f"  boot_part_size: {_q(BOOT_PART_SIZE)}",
        f"  root_part_size: {_q(ROOT_PART_SIZE)}",
        f"  name: {_q(img.name)}",
        "",
        "layer:",
        "  base: otp-rpios-lite",
        "  station: otp-rpios-setup",
    ]
    text = "\n".join(lines) + "\n"
    return RenderedConfig(text=text, files={}, summary={"name": img.name, "base": "Raspberry Pi OS Lite"})
