"""Per-board secrets (SPEC section 5).

* RSA-2048 boot-signing key (PKCS#8 private PEM / SPKI public PEM).
* ``customer_key_hash``: what the BCM2712 recovery firmware burns into OTP with ``program_pubkey=1``
  and reports as ``CUSTOMER_KEY_HASH``: SHA-256 over the 264-byte bootloader key blob
  (modulus as 256 little-endian bytes followed by the exponent as 8 little-endian bytes). Hashing the
  PEM or the DER SubjectPublicKeyInfo gives a different value.
* ``device_secret``: 32 random bytes (hex), root of the LUKS recovery passphrases
  ``HMAC-SHA256(device_secret, "<label>:<serial>")``.

And for the board's own OTP device key (``rpi-fw-crypto`` key-id 1, generated by the firmware and
exported by the fastboot gadget in the ``secure`` mode): parsing the exported key, checking it against
the public key the board reports, and the LUKS key the board derives from it.

Nothing in this module logs key material.
"""

from __future__ import annotations

import hashlib
import hmac
import re
import secrets as _secrets

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa

_HEX_RE = re.compile(r"^[0-9a-fA-F]+$")


def generate_rsa_keypair(bits: int = 2048) -> tuple[str, str]:
    """Generate an RSA key pair (e = 65537).

    :returns: ``(private_pem, public_pem)``: PKCS#8 unencrypted private key and SPKI public key,
        both ``str`` with ``\\n`` line endings.
    """
    # Note: the BCM2712 secure boot chain only accepts RSA-2048 (customer_key_hash enforces it).
    key = rsa.generate_private_key(public_exponent=65537, key_size=bits)
    priv = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ).decode("ascii")
    pub = key.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("ascii")
    return priv.replace("\r\n", "\n"), pub.replace("\r\n", "\n")


def _load_public_key(pem: str | bytes):
    """Load a public key from a public PEM (SPKI or PKCS#1) or derive it from a private PEM."""
    data = pem.encode("ascii") if isinstance(pem, str) else bytes(pem)
    if b"PRIVATE KEY" in data:
        try:
            return serialization.load_pem_private_key(data, password=None).public_key()
        except (ValueError, TypeError) as exc:
            raise ValueError(f"not a usable private key PEM: {type(exc).__name__}") from None
    try:
        return serialization.load_pem_public_key(data)
    except (ValueError, TypeError) as exc:
        raise ValueError(f"not a usable public key PEM: {type(exc).__name__}") from None


def customer_key_hash(public_pem: str) -> str:
    """SHA-256 of the bootloader key blob ``n (256 B LE) || e (8 B LE)``, 64 lowercase hex chars.

    Accepts a public PEM or a private PEM (its public half is used). Raises ``ValueError`` for
    anything that is not an RSA-2048 key.
    """
    key = _load_public_key(public_pem)
    if not isinstance(key, rsa.RSAPublicKey):
        raise ValueError("customer_key_hash needs an RSA public key")
    if key.key_size != 2048:
        raise ValueError(f"customer_key_hash needs an RSA-2048 key, got {key.key_size} bits")
    nums = key.public_numbers()
    blob = nums.n.to_bytes(256, "little") + nums.e.to_bytes(8, "little")
    return hashlib.sha256(blob).hexdigest()


def generate_device_secret() -> str:
    """32 random bytes from the OS CSPRNG, as 64 lowercase hex chars."""
    return _secrets.token_bytes(32).hex()


def luks_passphrase(device_secret_hex: str, label: str, serial: str) -> str:
    """LUKS recovery passphrase: ``HMAC-SHA256(bytes.fromhex(secret), f"{label}:{serial}")`` hex.

    ``label`` is the dm mapper name of the container (``osroot_crypt``), ``serial`` the 8-hex board
    serial. Deterministic, so the server can re-derive it to open a card offline.
    """
    s = (device_secret_hex or "").strip()
    if not s or len(s) % 2 or not _HEX_RE.match(s):
        raise ValueError("device secret must be a non-empty hex string")
    msg = f"{label}:{serial}".encode("utf-8")
    return hmac.new(bytes.fromhex(s), msg, hashlib.sha256).hexdigest()


def new_module_secrets() -> dict:
    """Fresh secrets for a new board.

    :returns: ``{"rsa_private_pem", "rsa_public_pem", "customer_key_hash", "device_secret"}``
    """
    priv, pub = generate_rsa_keypair()
    return {
        "rsa_private_pem": priv,
        "rsa_public_pem": pub,
        "customer_key_hash": customer_key_hash(pub),
        "device_secret": generate_device_secret(),
    }


def public_key_fingerprint(pem: str) -> str:
    """SHA-256 of the DER SubjectPublicKeyInfo, lowercase hex (any key type: RSA, EC, ...).

    Used for display of the board RSA key and of the OTP device key (``getvar:public-key``).
    A private PEM is accepted (its public half is fingerprinted). Raises ``ValueError`` on bad input.
    """
    key = _load_public_key(pem)
    der = key.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    return hashlib.sha256(der).hexdigest()


#: Order n of the NIST P-256 group: a device key is a scalar 1 <= d < n.
P256_ORDER = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551


def parse_device_private_key(data: bytes) -> tuple[int, str, str]:
    """``(d, private_pem, public_pem)`` of an OTP device key exported by the fastboot gadget.

    ``data`` is what ``rpi-fw-crypto privkey --key-id 1`` writes: the DER of an ECDSA P-256 private key
    (SEC1 or PKCS#8); the raw 32-byte scalar is accepted too. ``private_pem`` is PKCS#8, ``public_pem``
    SPKI. Raises ``ValueError`` (never with key material in the message) for anything else.
    """
    raw = bytes(data or b"")
    if len(raw) == 32:
        d = int.from_bytes(raw, "big")
        if not 1 <= d < P256_ORDER:
            raise ValueError("the exported device key is not a valid P-256 private scalar")
        key = ec.derive_private_key(d, ec.SECP256R1())
    else:
        try:
            key = serialization.load_der_private_key(raw, password=None)
        except (ValueError, TypeError) as exc:
            raise ValueError(f"the exported device key is not a DER private key ({type(exc).__name__})") from None
        if not isinstance(key, ec.EllipticCurvePrivateKey) or key.curve.name != "secp256r1":
            raise ValueError("the exported device key is not an ECDSA P-256 key")
        d = key.private_numbers().private_value
    priv = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                             serialization.NoEncryption()).decode("ascii")
    pub = key.public_key().public_bytes(serialization.Encoding.PEM,
                                        serialization.PublicFormat.SubjectPublicKeyInfo).decode("ascii")
    return d, priv.replace("\r\n", "\n"), pub.replace("\r\n", "\n")


def device_key_scalar(private_pem: str) -> int:
    """d of a stored device key (PKCS#8 PEM, as kept in ``device_private_pem``)."""
    key = serialization.load_pem_private_key(str(private_pem).encode("ascii"), password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey) or key.curve.name != "secp256r1":
        raise ValueError("the stored device key is not an ECDSA P-256 key")
    return key.private_numbers().private_value


def otp_zero_words(d: int) -> int:
    """How many of the 8 OTP words of d are zero.

    The firmware writes the 32-byte key as 8 OTP rows; a random key has a zero row with probability
    2^-32, so a zero row means the write was most likely cut short (power loss during key generation)
    and the key is weaker than 256 bits.
    """
    return sum(1 for i in range(8) if (d >> (32 * i)) & 0xFFFFFFFF == 0)


def same_public_key(a_pem: str, b_pem: str) -> bool:
    """Both PEMs (public or private) hold the same public key (compared as DER SPKI)."""
    try:
        ka, kb = _load_public_key(a_pem), _load_public_key(b_pem)
    except ValueError:
        return False
    fmt = (serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    return ka.public_bytes(*fmt) == kb.public_bytes(*fmt)


def luks_key(d: int, block_device_id: bytes) -> str:
    """The LUKS keyslot-0 passphrase the board derives for a storage device (64 lowercase hex).

    ``HMAC-SHA256(key = d as 32 big-endian bytes, msg = block_device_id)``, which the firmware computes
    for ``rpi-fw-crypto hmac --key-id 1`` (Raspberry Pi documents the key as the raw OTP value;
    confirm once on hardware). ``block_device_id`` is the exact sysfs text, e.g. the SD card CID
    ``/sys/block/mmcblk0/device/cid``: 32 lowercase hex characters plus one ``\n``.
    """
    if not 1 <= int(d) < P256_ORDER:
        raise ValueError("not a valid P-256 private scalar")
    return hmac.new(int(d).to_bytes(32, "big"), bytes(block_device_id), hashlib.sha256).hexdigest()


def public_pem_from_private(private_pem: str) -> str:
    """SPKI public PEM for a private PEM (used to repair records that lack ``rsa_public_pem``)."""
    key = _load_public_key(private_pem)
    return key.public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    ).decode("ascii")
