#!/usr/bin/env python3
"""Write ``layer/otp-rpios-packages.yaml``: the package set of an official Raspberry Pi OS Lite release.

Raspberry Pi publishes a ``.info`` file next to every image (``dpkg -l`` of the finished image)::

    python image/rpios_packages.py https://downloads.raspberrypi.com/raspios_lite_arm64/images/\
raspios_lite_arm64-2026-09-15/2026-09-15-raspios-trixie-arm64-lite.info

(a local path works too). Every installed package is listed, dependencies included: pi-gen installs with
recommends and rpi-image-gen without, so naming only pi-gen's top-level lists would give a smaller system.
Left out, because the station image is for the Raspberry Pi 5 only:

* the versioned kernel packages (``linux-image-6.12.47+rpt-rpi-2712`` ...): the ``linux-*-rpi-2712``
  metapackages pull the current ones;
* the Raspberry Pi 3/4 kernel (``linux-image-rpi-v8``, ``linux-headers-rpi-v8`` and their versioned packages).
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent / "layer" / "otp-rpios-packages.yaml"
VERSIONED_KERNEL = re.compile(r"^linux-(?:image|headers|kbuild)-\d")
OTHER_BOARDS = frozenset({"linux-image-rpi-v8", "linux-headers-rpi-v8"})


def read_info(src: str) -> str:
    if re.match(r"^https?://", src):
        with urllib.request.urlopen(src, timeout=60) as r:
            return r.read().decode("utf-8")
    return Path(src).read_text(encoding="utf-8")


def parse(info: str) -> tuple[str, str, list[str], list[str]]:
    """(release line, generator line, kept packages, dropped packages) of a ``.info`` file."""
    lines = info.splitlines()
    release = lines[0].strip() if lines else ""
    generator = lines[1].strip() if len(lines) > 1 else ""
    if not release.startswith("Raspberry Pi reference"):
        raise SystemExit(f"not a Raspberry Pi OS .info file (first line {release!r})")
    keep: list[str] = []
    drop: list[str] = []
    for line in lines:
        f = line.split()
        if len(f) < 4 or f[0] != "ii":
            continue
        name, arch = f[1], f[3]
        if name.endswith(":" + arch) and arch == "arm64":
            name = name[: -len(":arm64")]
        elif ":" not in name and arch not in ("arm64", "all"):
            name = f"{name}:{arch}"
        bare = name.split(":")[0]
        if VERSIONED_KERNEL.match(bare) or bare in OTHER_BOARDS:
            drop.append(name)
        else:
            keep.append(name)
    if len(keep) < 100:
        raise SystemExit(f"only {len(keep)} packages found: is this the .info of a Lite image?")
    return release, generator, sorted(set(keep)), sorted(set(drop))


def render(release: str, generator: str, keep: list[str], drop: list[str]) -> str:
    head = [
        "# METABEGIN",
        "# X-Env-Layer-Name: otp-rpios-packages",
        "# X-Env-Layer-Category: distribution",
        "# X-Env-Layer-Desc: The packages of an official Raspberry Pi OS Lite release",
        "#  (generated by image/rpios_packages.py from the release's .info file; do",
        "#  not edit by hand).",
        "# X-Env-Layer-Version: 1.0.0",
        "# METAEND",
        "---",
        f"# {release}",
        f"# {generator}",
        f"# {len(keep)} packages; left out (Raspberry Pi 5 image, the kernel metapackages pull the rest):",
    ]
    head += [f"#   {name}" for name in drop]
    body = ["mmdebstrap:", "  packages:"] + [f"    - {name}" for name in keep]
    return "\n".join(head + body) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    release, generator, keep, drop = parse(read_info(argv[1]))
    OUT.write_bytes(render(release, generator, keep, drop).encode("utf-8"))
    print(f"{OUT}: {len(keep)} packages from {release!r}, {len(drop)} left out")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
